[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
platform_packages =
    framework-espidf @ 3.50202.0
    toolchain-xtensa-esp-elf @ 13.2.0+20230928

; Enable USB CDC
board_build.usb_cdc = true
monitor_speed = 115200
monitor_port = COM6
